version: '3.6'
services:
  gateone:
    build: ./gateone
    ports:
    - "8000"
    hostname: kubectl
    networks:
    - web
    volumes:
    - ssh_key:/root/.ssh/
    - kube_config:/root/.kube/
    restart: always
    labels:
    - "traefik.enable=true"
    - "traefik.backend=gateone"
    - "traefik.port=8000"
    - "traefik.frontend.rule=Host:gateone.apps.hidevops.io"
  lab:
    build: ./lab
    ports:
    - "80"
    networks:
    - web
    restart: always
    labels:
    - "traefik.enable=true"
    - "traefik.backend=lab"
    - "traefik.port=80"
    - "traefik.frontend.rule=Host:cka.apps.hidevops.io"
networks:
    web:
      external: true
volumes:
  ssh_key: {}
  kube_config: {}
